version: '3.8'

services:
  postgres:
    container_name: fast-feet-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fastfeetdb
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
